### ISSUE TITLE
Wonky positioning

### ISSUE THREAD

**Issue by rmcauley** [owenmead/Pikaday#21] opened 2015-08-07 05:30 UTC
I've dropped in ownmead/Pikaday to add time selection over dbushell/Pikaday, but the Pikaday window appears in entirely the wrong place.  dbushell's appears in the correct space, but the current version here appears at left: -540px on my space.

This commit seems to be the one that fixes things for me if I start replacing Javascript: https://github.com/dbushell/Pikaday/commit/6ec802ca189a3c1830465308123a7d93bd6cdad1

**Comment by vandry** [comment] 2015-11-03 18:03
I have the same issue (mine appeared at -468px) and I worked around it without changing Pikaday code by specifying `reposition: false` in the options.

**Comment by owenmead** [comment] 2016-01-28 00:15
I've merged in upstream which should correct this issue.

**Closed by owenmead** 2016-01-28 00:15 UTC

**Comment by rmcauley** [comment] 2016-02-02 13:55
Thanks a lot! :)

**Comment by owenmead** [comment] 2016-02-02 18:10
So confirmed that the problem is solved on your end as well with the new version?

**Comment by rmcauley** [comment] 2016-02-03 00:55
Not confirmed, no, project is in a "it is working and I don't want to touch it" state. :)  However since you've pulled in the fix for it from upstream I'm happy to keep this closed and assume it works!
