### ISSUE TITLE
auto close after select min

### ISSUE THREAD

**Issue by godshades** [owenmead/Pikaday#45] opened 2016-08-02 06:37 UTC
i set autoClose: true but calendar auto close only after select date

**Comment by owenmead** [comment] 2017-08-01 04:28
autoClose is true by default, so setting it to true won't have any affect from normal behaviour.

There was back and forth on this. With time there are now multiple inputs. Closing on every input change event (hour, minute, date...) would be very annoying. Since you don't know when the user is "done" we only close on a date select. This is by design.

If you can come up with a slicker implementation, PR welcome.

**Closed by owenmead** 2017-08-01 04:28 UTC
